# Generated by Django 3.1.6 on 2021-02-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='account name'),
        ),
    ]
