# Generated by Django 3.1.6 on 2021-02-15 17:21

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210214_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to=register.models.user_img_upload_to, validators=[register.models.validate_is_picture]),
        ),
    ]
