# Generated by Django 3.1.6 on 2021-02-16 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210216_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_img', models.ImageField(default='default.png', upload_to=register.models.user_img_upload_to, validators=[register.models.validate_is_picture])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile_image_upload',
                'verbose_name_plural': 'ProfileImageUpload',
            },
        ),
    ]
