# Generated by Django 3.1.6 on 2021-02-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to=register.models.user_img_upload_to, validators=[register.models.validate_is_picture]),
        ),
    ]
