# Generated by Django 3.1.6 on 2021-02-19 13:56

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20210218_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.jpg', upload_to=register.models.user_img_upload_to, validators=[register.models.validate_is_picture]),
        ),
    ]
