# Generated by Django 3.1.6 on 2021-02-22 17:44

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20210219_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='upload_img',
            field=models.ImageField(default='media/profile_pics/default.png', upload_to=register.models.user_img_upload_to, validators=[register.models.validate_is_picture]),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.png', upload_to=register.models.user_img_upload_to, validators=[register.models.validate_is_picture]),
        ),
    ]
