# Generated by Django 3.1.6 on 2021-02-26 16:57

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20210223_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.png', upload_to=register.models.user_img_upload_to, validators=[register.models.validate_is_picture]),
        ),
    ]
