# Generated by Django 3.1.6 on 2021-02-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_auto_20210212_0239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
