# Generated by Django 3.1.6 on 2021-02-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0005_intimate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intimate',
        ),
    ]
