# Generated by Django 3.1.6 on 2021-02-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0007_intimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimate',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日'),
        ),
    ]
