# Generated by Django 3.1.6 on 2021-02-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0008_intimate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimate',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
