# Generated by Django 3.1.6 on 2021-02-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0009_intimate_reject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'PostComment'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'follow', 'verbose_name_plural': 'UserFollow'},
        ),
        migrations.AlterModelOptions(
            name='intimate',
            options={'verbose_name': 'intimate', 'verbose_name_plural': 'Intimate'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'UserPosts'},
        ),
    ]
